In [1]:
import keras
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.pooling import MaxPool2D
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
train_data


label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
5          0       0       0       0       0       0       0       0       0   
6          7       0       0       0       0       0       0       0       0   
7          3       0       0       0       0       0       0       0       0   
8          5       0       0       0       0       0       0       0       0   
9          3       0       0       0       0       0       0       0       0   
10         8       0       0       0       0       0       0       0       0   
11         9       0       0       0       0       0       0       0       0   
12         1       0       0       0       0       0       0       0       0   
13         3       0       0       0       0       0       0       0       0   
14         3       0       0       0       0       0       0       0       0   
15         1       0       0       0       0       0       0       0       0   
16         2       0       0       0       0       0       0       0       0   
17         0       0       0       0       0       0       0       0       0   
18         7       0       0       0       0       0       0       0       0   
19         5       0       0       0       0       0       0       0       0   
20         8       0       0       0       0       0       0       0       0   
21         6       0       0       0       0       0       0       0       0   
22         2       0       0       0       0       0       0       0       0   
23         0       0       0       0       0       0       0       0       0   
24         2       0       0       0       0       0       0       0       0   
25         3       0       0       0       0       0       0       0       0   
26         6       0       0       0       0       0       0       0       0   
27         9       0       0       0       0       0       0       0       0   
28         9       0       0       0       0       0       0       0       0   
29         7       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970      2       0       0       0       0       0       0       0       0   
41971      3       0       0       0       0       0       0       0       0   
41972      4       0       0       0       0       0       0       0       0   
41973      4       0       0       0       0       0       0       0       0   
41974      3       0       0       0       0       0       0       0       0   
41975      9       0       0       0       0       0       0       0       0   
41976      2       0       0       0       0       0       0       0       0   
41977      4       0       0       0       0       0       0       0       0   
41978      4       0       0       0       0       0       0       0       0   
41979      4       0       0       0       0       0       0       0       0   
41980      7       0       0       0       0       0       0       0       0   
41981      2       0       0       0       0       0       0       0       0   
41982      8       0       0       0       0       0       0       0       0   
41983      7       0       0       0       0       0       0       0       0   
41984      3       0       0       0       0       0       0       0       0   
41985      3       0       0       0       0       0       0       0       0   
41986      0       0       0       0       0       0       0       0       0   
41987      5       0       0       0       0       0       0       0       0   
41988  

In [4]:
test_data


pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       0       0       0       0       0       0       0   
12          0       0       0       0       0       0       0       0       0   
13          0       0       0       0       0       0       0       0       0   
14          0       0       0       0       0       0       0       0       0   
15          0       0       0       0       0       0       0       0       0   
16          0       0       0       0       0       0       0       0       0   
17          0       0       0       0       0       0       0       0       0   
18          0       0       0       0       0       0       0       0       0   
19          0       0       0       0       0       0       0       0       0   
20          0       0       0       0       0       0       0       0       0   
21          0       0       0       0       0       0       0       0       0   
22          0       0       0       0       0       0       0       0       0   
23          0       0       0       0       0       0       0       0       0   
24          0       0       0       0       0       0       0       0       0   
25          0       0       0       0       0       0       0       0       0   
26          0       0       0       0       0       0       0       0       0   
27          0       0       0       0       0       0       0       0       0   
28          0       0       0       0       0       0       0       0       0   
29          0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27970       0       0       0       0       0       0       0       0       0   
27971       0       0       0       0       0       0       0       0       0   
27972       0       0       0       0       0       0       0       0       0   
27973       0       0       0       0       0       0       0       0       0   
27974       0       0       0       0       0       0       0       0       0   
27975       0       0       0       0       0       0       0       0       0   
27976       0       0       0       0       0       0       0       0       0   
27977       0       0       0       0       0       0       0       0       0   
27978       0       0       0       0       0       0       0       0       0   
27979       0       0       0       0       0       0       0       0       0   
27980       0       0       0       0       0       0       0       0       0   
27981       0       0       0       0       0       0       0       0       0   
27982       0       0       0       0       0       0       0       0       0   
27983       0       0       0       0       0       0       0       0       0   
27984       0       0       0       0       0       0       0       0       0   
27985       0       0       0       0       0       0       0       0       0   
27986       0       0       0       0       0       0       0       0       0   
27987       0       0       0       0 

In [5]:
labels = train_data.iloc[:,0].values

In [6]:
labels

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [7]:
features = train_data.iloc[:,1:].values.reshape(len(train_data),28,28,1) # convolution requires in 4d, each row represent an image of size 28 X 28 X 1 channel is 1 cuz the image is b/w

In [8]:
features


array([[[[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        ..., 
        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        ..., 
        [[0],
         [0],
         [0],
         ..., 
    

In [9]:
labels = keras.utils.to_categorical(labels, num_classes = 10)

In [10]:
labels
labels.shape

(42000, 10)

In [13]:
labels = np.array(labels)
labels.shape
features = np.array(features)
features.shape

(42000, 28, 28, 1)

In [14]:
# splitting train test data
train_x, test_x, train_y, test_y = train_test_split(features,labels, test_size = 0.2, random_state=1)

In [15]:
train_x.shape


(33600, 28, 28, 1)

In [28]:
# Model

def LeNet(length, width, output, channels):
    model = Sequential()
    model.add(Conv2D(filters=32, kernel_size=(3,3), strides=(2,2),input_shape = (length,width,channels)))
    model.add(Activation('relu'))
    model.add(MaxPool2D(pool_size = (2,2)))
    model.add(Conv2D(filters=64, kernel_size=(3,3), strides=(2,2)))
    model.add(Activation('relu'))
    model.add(MaxPool2D(pool_size = (2,2)))
    model.add(Flatten())
    model.add(Dense(100))
    model.add(Activation('relu'))
    model.add(Dense(output))
    model.add(Activation('softmax'))
    return model

In [29]:
model = LeNet(28,28,10,1)

In [31]:

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 13, 13, 64)        640       
_________________________________________________________________
activation_9 (Activation)    (None, 13, 13, 64)        0         
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 2, 2, 128)         73856     
_________________________________________________________________
activation_10 (Activation)   (None, 2, 2, 128)         0         
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 1, 1, 128)         0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 128)               0         
__________

In [32]:
# train the model
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [44]:
epochs = 60

In [45]:
model.fit(train_x,train_y,validation_data=(test_x,test_y),epochs=epochs)

Train on 33600 samples, validate on 8400 samples
Epoch 1/60
33600/33600 [==============================] - 8s 244us/step - loss: 0.0041 - acc: 0.9992 - val_loss: 0.2571 - val_acc: 0.9749
Epoch 2/60
33600/33600 [==============================] - 8s 245us/step - loss: 0.0026 - acc: 0.9995 - val_loss: 0.2748 - val_acc: 0.9721
Epoch 3/60
33600/33600 [==============================] - 8s 251us/step - loss: 0.0024 - acc: 0.9996 - val_loss: 0.2474 - val_acc: 0.9757
Epoch 4/60
33600/33600 [==============================] - 8s 242us/step - loss: 0.0032 - acc: 0.9991 - val_loss: 0.2814 - val_acc: 0.9739
Epoch 5/60
33600/33600 [==============================] - 8s 242us/step - loss: 0.0026 - acc: 0.9995 - val_loss: 0.2649 - val_acc: 0.9725
Epoch 6/60
33600/33600 [==============================] - 8s 239us/step - loss: 0.0035 - acc: 0.9993 - val_loss: 0.2369 - val_acc: 0.9762
Epoch 7/60
33600/33600 [==============================] - 8s 239us/step - loss: 0.0019 - acc: 0.9996 - val_loss: 0.2433 - v

33600/33600 [==============================] - 8s 242us/step - loss: 4.7983e-04 - acc: 1.0000 - val_loss: 0.2567 - val_acc: 0.9762
Epoch 59/60
33600/33600 [==============================] - 8s 242us/step - loss: 4.7983e-04 - acc: 1.0000 - val_loss: 0.2566 - val_acc: 0.9762
Epoch 60/60
33600/33600 [==============================] - 8s 245us/step - loss: 4.7983e-04 - acc: 1.0000 - val_loss: 0.2566 - val_acc: 0.9762


In [46]:
model.save_weights('cnn_mnist_digit.h5')

In [47]:

model.load_weights('cnn_mnist_digit.h5')

In [49]:
test_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [50]:
test_set = test_data.iloc[:,:].values.reshape(len(test_data),28,28,1)

In [51]:
test_set

array([[[[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        ..., 
        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ..., 
         [0],
         [0],
         [0]],

        ..., 
        [[0],
         [0],
         [0],
         ..., 
    

In [52]:
prediction = model.predict(test_set)

In [54]:
prediction = np.argmax(prediction, axis=1)
prediction

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [55]:
#for Kaggle: Writing prediction to CSV File
df = pd.DataFrame({
    'S.N.' : list(range(1,len(prediction)+1)),
    'Output' : prediction
})

df.to_csv("prediction.csv", index=False, header=True)